blog_images/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('images/', include('images.urls', namespace='images')),
    path('posts/', include('pages.urls', namespace='posts'))
]

#print(urlpatterns)

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) # [path('media/<int:year>/<int:month>/<int:day>/<slug:name>/')]

#print(urlpatterns)

images/urls.py
from django.urls import path

from images.views import images_list_view

app_name = 'images'

urlpatterns = [
    path('', images_list_view, name='imgs'),
]

pages/urls.py
from django.urls import path

from pages.views import post_list_view

app_name = 'pages'

urlpatterns = [
    path('posts/<int:page_num>/', post_list_view, name='posts'),
    path('posts/', post_list_view, name='first_posts'),
]

images/models.py
from django.db import models


class Image(models.Model):
    title = models.CharField(max_length=32)
    create_date = models.DateTimeField(auto_now_add=True)
    image = models.ImageField(upload_to='%Y/%m/%d')

    def __str__(self):
        return self.title

pages/models.py
from django.contrib.auth.models import User
from django.db import models


class Post(models.Model):
    title = models.CharField(max_length=32)
    text = models.TextField(blank=False)
    published = models.BooleanField(default=False)
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    create_date = models.DateTimeField(auto_now_add=True)
    edit_date = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.title

images/views.py
from django.shortcuts import render

from images.models import Image


def images_list_view(request):
    image_list = Image.objects.all()
    return render(request, 'images/images.html',
                  context={'images': image_list})

pages/views.py
from django.core.paginator import Paginator, EmptyPage
from django.shortcuts import render

from pages.models import Post


def post_list_view(request, page_num=1):
    posts = Post.objects.filter(published=True)

    paginator = Paginator(posts, 2)

    try:
        page_object = paginator.page(page_num)
    except EmptyPage:
        if page_num < 1:
            page_object = paginator.page(1)
        else:
            page_object = paginator.page(paginator.num_pages)
    """
    page_object.has_previous() - есть ли предыдущая страница?
    page_object.previous_page_number() - получить номер предыдущей страницы
    """

    return render(request, 'pages/post_list.html', {'page': page_object})

images/templates/images/images.html
{% extends 'root.html' %}

{% block content %}
    {% for image in images %}
        <div>
            <h3>{{ image.title }}</h3>
            <img src="{{ image.image.url }}">
        </div>
    {% endfor %}
{%endblock%}

pages/templates/pages/post_list.html
{% extends 'root.html' %}

{% block content %}

    {% for post in page %}
        <div>
            <h3>{{post.title}}</h3>
            <p>{{post.text|truncatechars:30}}</p>
            <p>{{post.author}}</p>
        </div>
    {% endfor %}

    <div style="display: flex; align-items: center;">
        {% if page.has_previous %}
            <a href="{% url 'posts:posts' page.previous_page_number %}">< </a>
        {% endif %}
        <p> {{page.number}} </p>
        {% if page.has_next %}
            <a href="{% url 'posts:posts' page.next_page_number %}"> ></a>
        {% endif %}
    </div>

{% endblock %}

templates/root.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{{ title|default:'Катинка' }}</title>
</head>
<body>
    <div>
        {% block content %}
        {%endblock%}
    </div>
</body>
</html>